apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
stringData:
  PLACEHOLDER: nothing #PLACEHOLDER is a label that is used to store sensitive data such as passwords, API keys, and other secrets. we put as nothing for now since we don't have any sensitive data to store
type: Opaque
